name: E2E on Chrome

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  Cypress-Run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'  # Ensuring Node.js version 18.12.0 is installed

      - name: Verify Node.js Version
        run: node -v  # This will help us check the Node.js version in the logs

      - name: Install Dependencies
        run: |
          corepack enable  # Ensure pnpm is available
          corepack prepare pnpm@latest --activate  # Install and activate the latest pnpm
          pnpm install  # Install dependencies using pnpm
        working-directory: ./axleWebsite

      - name: Cypress run
        run: cypress run --config-file=cypress.config.js
        working-directory: ./axleWebsite
        with:
          browser: chrome
